/**
 * Turn a VERIFIED build into what ships (§12.C step 6).
 *
 * Run:  cd rakk-app && npx tsx ../pipeline/emit.ts
 *
 * Writes:
 *   supabase/migrations/NNNN_ingredient_release_<version>.sql
 *       the rows, the name-lookup table and a release record — one reviewable,
 *       versioned file per dataset build (§11)
 *   rakk-app/src/data/catalog/bundled.json
 *       §8's offline subset: the curated common set plus the everyday
 *       allow-list, as built (so offline and online agree on every field)
 *
 * Refuses to run unless out/verify-report.json is newer than the build and
 * has no failures — nothing unverified reaches the app.
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Ingredient } from '../rakk-app/src/types/ingredient';
import { needlesFor } from '../rakk-app/src/services/matcher';
import { SEED_INGREDIENTS } from '../rakk-app/src/data/seed';

const ROOT = dirname(fileURLToPath(import.meta.url));
const REPO = join(ROOT, '..');
const OUT = join(ROOT, 'out');
const MIGRATIONS = join(REPO, 'supabase/migrations');

const ingredientsPath = join(OUT, 'ingredients.json');
const verifyPath = join(OUT, 'verify-report.json');
const verify = JSON.parse(readFileSync(verifyPath, 'utf8'));
if (statSync(verifyPath).mtimeMs < statSync(ingredientsPath).mtimeMs) {
  console.error('verify-report.json is older than the build. Run verify.ts first.');
  process.exit(1);
}
if (verify.failures.length) {
  console.error(`verification has ${verify.failures.length} failures — refusing to emit.`);
  process.exit(1);
}

const raw = readFileSync(ingredientsPath, 'utf8');
const rows: Ingredient[] = JSON.parse(raw);
const report = JSON.parse(readFileSync(join(OUT, 'build-report.json'), 'utf8'));
const version = `${report.built_at.slice(0, 10)}.${createHash('sha256').update(raw).digest('hex').slice(0, 8)}`;

// ─── the name lookup, from the matcher's own function ───
const names: Record<string, string[]> = {};
const owner = new Map<string, string>();
for (const r of rows) {
  const needles = needlesFor(r);
  for (const n of needles) {
    const o = owner.get(n);
    if (o && o !== r.id) throw new Error(`needle "${n}" claimed by ${o} and ${r.id} — verify should have caught this`);
    owner.set(n, r.id);
  }
  if (needles.length) names[r.id] = needles;
}

// ─── SQL ───
const TAG = '$rakk_data$';
const data = JSON.stringify(rows.map((r) => ({ ...r, dataset_version: version })));
const namesJson = JSON.stringify(names);
if (data.includes(TAG) || namesJson.includes(TAG)) throw new Error('dollar-quote tag occurs in the data');

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const COLUMNS = ['canonical_name', 'aka', 'cas_number', 'e_number_ins_code', 'chemical_formula', 'category', 'origin', 'typical_uses', 'allergen_flags', 'plain_explanation', 'jurisdictions', 'risk_assessment_refs', 'usage_context', 'source', 'source_updated_at', 'last_full_review_at', 'everyday_allowlist', 'dataset_version'];

const sources = Object.fromEntries(Object.entries(report.sources).map(([k, v]: any) => [k, { fetched_at: v.fetched_at, sha256: v.sha256, ecfr_date: v.ecfr_date, celex: v.celex, source_last_updated: v.source_last_updated }]));

const sql = `-- Ingredient dataset release ${version}
--
-- GENERATED by pipeline/emit.ts from a verified build — do not edit by hand.
-- To change a row, change the pipeline or the seed and rebuild.
--
--   rows ${rows.length} · names ${owner.size} · built ${report.built_at}
--   verification: ${Object.values(verify.passed).reduce((a: number, b: any) => a + b, 0)} checks passed, 0 failed
--
-- Provenance for every field (source, locator, verbatim excerpt) is in
-- pipeline/out/provenance.json at the commit that added this file.

insert into public.ingredient_dataset_releases (version, built_at, row_count, sources, notes)
values (${q(version)}, ${q(report.built_at)}, ${rows.length}, ${q(JSON.stringify(sources))}::jsonb,
        ${q(`counts: ${JSON.stringify(report.counts)}`)})
on conflict (version) do nothing;

with incoming as (
  select * from jsonb_populate_recordset(null::public.ingredients, ${TAG}${data}${TAG}::jsonb)
)
insert into public.ingredients (id, ${COLUMNS.join(', ')})
select id, ${COLUMNS.join(', ')} from incoming
on conflict (id) do update set
${COLUMNS.map((c) => `  ${c} = excluded.${c}`).join(',\n')};

-- Names are rebuilt whole: they are derived data, and a partial update could
-- briefly let one name point at two ingredients.
delete from public.ingredient_names;
insert into public.ingredient_names (needle, ingredient_id)
select needle, e.key
  from jsonb_each(${TAG}${namesJson}${TAG}::jsonb) as e(key, value),
       jsonb_array_elements_text(e.value) as needle;

-- Rows this release no longer contains.
delete from public.ingredients where dataset_version <> ${q(version)};
`;

// A release migration that is not yet committed has not been deployed, so a
// rebuild replaces it instead of stacking a second release behind it. Once
// committed, a release is history: the next build gets a new file.
const committed = (f: string) => {
  try { execFileSync('git', ['ls-files', '--error-unmatch', join(MIGRATIONS, f)], { cwd: REPO, stdio: 'ignore' }); return true; } catch { return false; }
};
let existing = readdirSync(MIGRATIONS).filter((f) => /^\d{4}_/.test(f)).sort();
for (const f of existing.filter((f) => f.includes('_ingredient_release_') && !committed(f) && !f.includes(version.replace('.', '_')))) {
  unlinkSync(join(MIGRATIONS, f));
  console.log(`  replaced uncommitted ${f}`);
}
existing = readdirSync(MIGRATIONS).filter((f) => /^\d{4}_/.test(f)).sort();
const already = existing.find((f) => f.includes(version.replace('.', '_')));
const next = already ?? `${String(Number(existing.at(-1)!.slice(0, 4)) + 1).padStart(4, '0')}_ingredient_release_${version.replace('.', '_')}.sql`;
writeFileSync(join(MIGRATIONS, next), sql);

// ─── the bundled offline subset (§8) ───
const seedIds = new Set(SEED_INGREDIENTS.map((i) => i.id));
const bundled = rows.filter((r) => seedIds.has(r.id) || r.everyday_allowlist);
const catalogDir = join(REPO, 'rakk-app/src/data/catalog');
mkdirSync(catalogDir, { recursive: true });
writeFileSync(join(catalogDir, 'bundled.json'), JSON.stringify({ version, rows: bundled }) + '\n');

console.log(`release ${version}`);
console.log(`  ${next}  (${(sql.length / 1e6).toFixed(1)} MB, ${rows.length} rows, ${owner.size} names)`);
console.log(`  rakk-app/src/data/catalog/bundled.json  (${bundled.length} rows, ${(JSON.stringify(bundled).length / 1e3).toFixed(0)} kB)`);
