-- The ingredient database — §11, served per §7.
--
-- Columns are rakk-app/src/types/ingredient.ts field for field, in the spec's
-- own snake_case, so the Phase 1 → Phase 2 cutover is a data swap (§10 step 8).
-- The rows themselves arrive in separate, generated dataset-release migrations
-- (pipeline/emit-sql.ts), one per build, so every change to the data is a
-- reviewable, versioned file (§11: "its own versioned table").
--
-- NOTE ON NAMING: there is no score, grade, rating or verdict column, and there
-- must never be one. `risk_assessment_refs` holds citation links; it is §11's
-- own field name and carries no judgment.

create extension if not exists pg_trgm with schema extensions;

-- ─── releases ───────────────────────────────────────────────────────────────
-- One row per imported build. The app compares `version` with the one its
-- cached rows came from, and refreshes them when it moves (§7: the bundled
-- subset is "a cache, not the source of truth").
create table if not exists public.ingredient_dataset_releases (
  version      text        primary key,
  built_at     timestamptz not null,
  imported_at  timestamptz not null default now(),
  row_count    int         not null,
  sources      jsonb       not null,
  notes        text
);

-- ─── ingredients ────────────────────────────────────────────────────────────
create table if not exists public.ingredients (
  id                   text    primary key,
  canonical_name       text    not null,
  aka                  text[]  not null default '{}',
  cas_number           text,
  e_number_ins_code    text,
  chemical_formula     text,
  category             text    not null check (category in (
                         'preservative', 'thickener', 'emulsifier', 'filler', 'colorant', 'flavor',
                         'sweetener', 'acidity_regulator', 'leavening_agent', 'antioxidant', 'other')),
  origin               text    not null check (origin in ('natural', 'nature_identical', 'synthetic', 'unknown')),
  typical_uses         text[]  not null default '{food}',
  allergen_flags       text[]  not null default '{}',
  plain_explanation    text    not null,
  -- [{jurisdiction, status, citation, citation_url}] — status is the
  -- regulator's own wording, deliberately not an enum (see ingredient.ts).
  jurisdictions        jsonb   not null default '[]',
  risk_assessment_refs text[],
  -- {threshold_of_concern, typical_concentration_range, product_type_context}
  usage_context        jsonb,
  source               text    not null check (source in (
                         'fda_substances_added_to_food', 'fda_gras_notice', 'codex_alimentarius',
                         'usda_fooddata_central', 'manual_curation',
                         'fda_color_additives', 'eu_additives_regulation')),
  source_updated_at    date    not null,
  last_full_review_at  date,
  everyday_allowlist   boolean not null default false,
  -- Not part of the app contract: which release last wrote this row.
  dataset_version      text    not null references public.ingredient_dataset_releases (version),

  -- §11: no dosage claim without a traceable source — enforced here too, not
  -- only in the build.
  constraint usage_context_has_source check (
    usage_context is null or coalesce(array_length(risk_assessment_refs, 1), 0) > 0
  )
);

create index if not exists ingredients_cas_idx on public.ingredients (cas_number);
create index if not exists ingredients_e_number_idx on public.ingredients (e_number_ins_code);

-- ─── name lookup ────────────────────────────────────────────────────────────
-- Every string that finds an ingredient in a label, exactly as the app's
-- matcher derives them (`needlesFor` in rakk-app/src/services/matcher.ts) —
-- generated by the pipeline from that same function, never re-derived here,
-- so the database and the matcher cannot disagree about what a name is.
--
-- `needle` is the primary key: one name, one ingredient (PHASE-2-HANDOFF §1).
create table if not exists public.ingredient_names (
  needle        text primary key,
  ingredient_id text not null references public.ingredients (id) on delete cascade
);
create index if not exists ingredient_names_ingredient_idx on public.ingredient_names (ingredient_id);
-- §6/§7's trigram index. Exact lookup is what matching uses; this is here for
-- near-miss suggestions on unmatched names ("sodium benzoat"), which must be
-- offered to a person, never auto-applied.
create index if not exists ingredient_names_trgm_idx on public.ingredient_names using gin (needle extensions.gin_trgm_ops);

/**
 * Which of these label phrases name an ingredient? Returns those ingredients.
 *
 * The client sends every run of whole words in the printed list
 * (`candidatePhrases`); this answers with exactly the rows the on-device
 * matcher would have claimed had it held the whole database. The client never
 * needs the full database (§7), and the Label screen's result is identical.
 */
create or replace function public.lookup_ingredients(phrases text[])
returns setof public.ingredients
language sql
stable
security invoker
set search_path = public
as $$
  select distinct i.*
    from public.ingredient_names n
    join public.ingredients i on i.id = n.ingredient_id
   where n.needle = any (phrases[1:3000]);
$$;

-- ─── unmatched-ingredient backlog (§12.B, §14) ──────────────────────────────
-- "Log any ingredient your app encounters at runtime that still isn't matched
-- … and batch-process that backlog." Privacy (§14): the printed name and the
-- product barcode only — no user id, no photo, nothing that rebuilds a
-- person's shopping history.
create table if not exists public.unmatched_ingredient_log (
  id           bigint generated always as identity primary key,
  printed_name text        not null check (char_length(printed_name) between 1 and 160),
  barcode      text        check (barcode is null or barcode ~ '^[0-9]{6,14}$'),
  scan_method  text        check (scan_method in ('barcode', 'photo_ocr', 'manual_search')),
  seen_at      timestamptz not null default now()
);
create index if not exists unmatched_ingredient_log_name_idx on public.unmatched_ingredient_log (lower(printed_name));

create or replace function public.log_unmatched_ingredients(names text[], barcode text, scan_method text)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.unmatched_ingredient_log (printed_name, barcode, scan_method)
  select left(trim(n), 160), barcode, scan_method
    from unnest(names[1:40]) as n
   where trim(n) <> '';
$$;

-- The backlog view the curation pass works from: most-seen first (§12.B2's
-- "prioritise by scan frequency").
create or replace view public.unmatched_ingredient_backlog
with (security_invoker = true) as
  select lower(printed_name) as printed_name,
         count(*)            as times_seen,
         count(distinct barcode) as products,
         max(seen_at)        as last_seen
    from public.unmatched_ingredient_log
   group by lower(printed_name)
   order by times_seen desc;

-- ─── access ─────────────────────────────────────────────────────────────────
-- §7: "The Ingredient and base Product tables are public-read via row-level
-- security policies — no reason to gate ingredient facts behind a login."
alter table public.ingredients                 enable row level security;
alter table public.ingredient_names            enable row level security;
alter table public.ingredient_dataset_releases enable row level security;
alter table public.unmatched_ingredient_log    enable row level security;

drop policy if exists "ingredients are public" on public.ingredients;
create policy "ingredients are public" on public.ingredients for select to anon, authenticated using (true);
drop policy if exists "ingredient names are public" on public.ingredient_names;
create policy "ingredient names are public" on public.ingredient_names for select to anon, authenticated using (true);
drop policy if exists "releases are public" on public.ingredient_dataset_releases;
create policy "releases are public" on public.ingredient_dataset_releases for select to anon, authenticated using (true);
-- unmatched_ingredient_log: RLS on, no policy — only the logging function
-- (security definer) writes, and only the service role reads.

grant select on public.ingredients, public.ingredient_names, public.ingredient_dataset_releases to anon, authenticated;
revoke insert, update, delete on public.ingredients, public.ingredient_names, public.ingredient_dataset_releases from anon, authenticated;
revoke all on public.unmatched_ingredient_log from anon, authenticated;
revoke all on public.unmatched_ingredient_backlog from anon, authenticated;
grant execute on function public.lookup_ingredients(text[]) to anon, authenticated;
grant execute on function public.log_unmatched_ingredients(text[], text, text) to anon, authenticated;
